import { Play } from 'next/font/google';
import './styles/global.scss';

const play = Play({ 
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={play.className}>{children}</body>
    </html>
  )
}
